name: Quarkdown Environment Setup
description: Sets up Quarkdown execution environment
inputs: {}

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4