name: Quarkdown Environment Setup
description: Sets up Quarkdown execution environment
inputs:
  full-checkout:
    description: "If true, fetches full history and tags. Defaults to false."
    default: true # TODO default to false

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.full-checkout && '0' || '1' }}
        fetch-tags: ${{ inputs.full-checkout }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4