# This workflow will build the project with Gradle and release its build.

name: Gradle test

on:
  workflow_call:
  push:
    branches-ignore: [ "main", "workflow-test" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: iamgio/quarkdown/.github/actions/setup-environment@pckg-managers # TODO bring back to main
      with:
        full-checkout: ${{ inputs.full-checkout }}

    # TODO THIS IS A TEST!
    - name: Extract version
      id: extract-version
      # Strip a string prefix from the git tag name:
      run: |
        echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - uses: mislav/bump-homebrew-formula-action@v3
      with:
        formula-name: quarkdown
        homebrew-tap: 'quarkdown-labs/homebrew-quarkdown'
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

    - name: Run tests
      uses: burrunan/gradle-cache-action@v3
      with:
        job-id: main
        arguments: ktlintCheck test
