# This workflow will build the project with Gradle and release its build.

name: Gradle test

on:
  workflow_call:
  push:
    branches-ignore: [ "main", "workflow-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: iamgio/quarkdown/.github/actions/setup-environment@workflow-test
      with:
        full-checkout: ${{ inputs.full-checkout }}

    - name: Run ktlint check
      run: ./gradlew ktlintCheck

    - name: Run tests
      run: ./gradlew test
