# This workflow will build the project with Gradle and release its build.

name: Gradle deploy

on:
  push:
    branches: [ "main", "workflow-test" ]

jobs:
  test:
    uses: iamgio/quarkdown/.github/workflows/gradle-test.yml@main

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: iamgio/quarkdown/.github/actions/setup-environment@main

    - name: Build distribution
      run: ./gradlew clean build distZip

    - name: Echo output files
      run: ls -d "$PWD/build/"*

    - name: Distribute artifact
      uses: actions/upload-artifact@v4
      with:
        name: quarkdown
        path: build/distributions/quarkdown.zip

    - name: Create devbuild release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: Development build
        files: build/distributions/quarkdown.zip

    - name: Generate docs
      run: ./gradlew dokkaGeneratePublicationHtml

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/dokka

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0