# This workflow will build the project with Gradle and release its build.

name: Gradle test

on:
  workflow_call:
  push:
    branches-ignore: [ "main", "workflow-test" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: iamgio/quarkdown/.github/actions/setup-environment@main
      with:
        full-checkout: ${{ inputs.full-checkout }}

    - name: Run tests
      uses: burrunan/gradle-cache-action@v3
      with:
        job-id: main
        arguments: ktlintCheck test