on:
  push:
    tags: [ "TEST" ]

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: quarkdown
          homebrew-tap: 'quarkdown-labs/homebrew-quarkdown'
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}